<?php

Autoloader::add_classes(array(

	'Elastica_Client' => __DIR__.'/lib/Elastica/Client.php',
	'Elastica_Cluster' => __DIR__.'/lib/Elastica/Cluster.php',
	'Elastica_Document' => __DIR__.'/lib/Elastica/Document.php',
	'Elastica_Index' => __DIR__.'/lib/Elastica/Index.php',
	'Elastica_Log' => __DIR__.'/lib/Elastica/Log.php',
	'Elastica_Node' => __DIR__.'/lib/Elastica/Node.php',
	'Elastica_Param' => __DIR__.'/lib/Elastica/Param.php',
	'Elastica_Percolator' => __DIR__.'/lib/Elastica/Percolator.php',
	'Elastica_Query' => __DIR__.'/lib/Elastica/Query.php',
	'Elastica_Request' => __DIR__.'/lib/Elastica/Request.php',
	'Elastica_Response' => __DIR__.'/lib/Elastica/Response.php',
	'Elastica_Result' => __DIR__.'/lib/Elastica/Result.php',
	'Elastica_ResultSet' => __DIR__.'/lib/Elastica/ResultSet.php',
	'Elastica_Script' => __DIR__.'/lib/Elastica/Script.php',
	'Elastica_ScriptFields' => __DIR__.'/lib/Elastica/ScriptFields.php',
	'Elastica_Search' => __DIR__.'/lib/Elastica/Search.php',
	'Elastica_Searchable' => __DIR__.'/lib/Elastica/Searchable.php',
	'Elastica_Status' => __DIR__.'/lib/Elastica/Status.php',
	'Elastica_Type' => __DIR__.'/lib/Elastica/Type.php',
	'Elastica_Util' => __DIR__.'/lib/Elastica/Util.php',

	'Elastica_Cluster_Settings' => __DIR__.'/lib/Elastica/Cluster/Settings.php',	

	'Elastica_Exception_Abstract' => __DIR__.'/lib/Elastica/Exception/Abstract.php',
	'Elastica_Exception_BulkResponse' => __DIR__.'/lib/Elastica/Exception/BulkResponse.php',
	'Elastica_Exception_Client' => __DIR__.'/lib/Elastica/Exception/Client.php',
	'Elastica_Exception_Invalid' => __DIR__.'/lib/Elastica/Exception/Invalid.php',
	'Elastica_Exception_NotFound' => __DIR__.'/lib/Elastica/Exception/NotFound.php',
	'Elastica_Exception_NotImplemented' => __DIR__.'/lib/Elastica/Exception/NotImplemented.php',
	'Elastica_Exception_Response' => __DIR__.'/lib/Elastica/Exception/Response.php',

	'Elastica_Facet_Abstract' => __DIR__.'/lib/Elastica/Facet/Abstract.php',
	'Elastica_Facet_DateHistogram' => __DIR__.'/lib/Elastica/Facet/DateHistogram.php',
	'Elastica_Facet_Filter' => __DIR__.'/lib/Elastica/Facet/Filter.php',
	'Elastica_Facet_GeoDistance' => __DIR__.'/lib/Elastica/Facet/GeoDistance.php',
	'Elastica_Facet_Histogram' => __DIR__.'/lib/Elastica/Facet/Histogram.php',
	'Elastica_Facet_Query' => __DIR__.'/lib/Elastica/Facet/Query.php',
	'Elastica_Facet_Range' => __DIR__.'/lib/Elastica/Facet/Range.php',
	'Elastica_Facet_Statistical' => __DIR__.'/lib/Elastica/Facet/Statistical.php',
	'Elastica_Facet_Terms' => __DIR__.'/lib/Elastica/Facet/Terms.php',
	'Elastica_Facet_TermsStats' => __DIR__.'/lib/Elastica/Facet/TermsStats.php',
	
	'Elastica_Filter_Abstract_Multi' => __DIR__.'/lib/Elastica/Filter/Abstract/Multi.php',
	'Elastica_Filter_Abstract' => __DIR__.'/lib/Elastica/Filter/Abstract.php',
	'Elastica_Filter_And' => __DIR__.'/lib/Elastica/Filter/And.php',
	'Elastica_Filter_Bool' => __DIR__.'/lib/Elastica/Filter/Bool.php',
	'Elastica_Filter_Exists' => __DIR__.'/lib/Elastica/Filter/Exists.php',
	'Elastica_Filter_GeoBoundingBox' => __DIR__.'/lib/Elastica/Filter/GeoBoundingBox.php',
	'Elastica_Filter_GeoDistance' => __DIR__.'/lib/Elastica/Filter/GeoDistance.php',
	'Elastica_Filter_GeoPolygon' => __DIR__.'/lib/Elastica/Filter/GeoPolygon.php',
	'Elastica_Filter_HasChild' => __DIR__.'/lib/Elastica/Filter/HasChild.php',
	'Elastica_Filter_Ids' => __DIR__.'/lib/Elastica/Filter/Ids.php',
	'Elastica_Filter_Limit' => __DIR__.'/lib/Elastica/Filter/Limit.php',
	'Elastica_Filter_MatchAll' => __DIR__.'/lib/Elastica/Filter/MatchAll.php',
	'Elastica_Filter_Missing' => __DIR__.'/lib/Elastica/Filter/Missing.php',
	'Elastica_Filter_Nested' => __DIR__.'/lib/Elastica/Filter/Nested.php',
	'Elastica_Filter_Not' => __DIR__.'/lib/Elastica/Filter/Not.php',
	'Elastica_Filter_NumericRange' => __DIR__.'/lib/Elastica/Filter/NumericRange.php',
	'Elastica_Filter_Or' => __DIR__.'/lib/Elastica/Filter/Or.php',
	'Elastica_Filter_Prefix' => __DIR__.'/lib/Elastica/Filter/Prefix.php',
	'Elastica_Filter_Query' => __DIR__.'/lib/Elastica/Filter/Query.php',
	'Elastica_Filter_Range' => __DIR__.'/lib/Elastica/Filter/Range.php',
	'Elastica_Filter_Script' => __DIR__.'/lib/Elastica/Filter/Script.php',
	'Elastica_Filter_Term' => __DIR__.'/lib/Elastica/Filter/Term.php',
	'Elastica_Filter_Terms' => __DIR__.'/lib/Elastica/Filter/Terms.php',
	'Elastica_Filter_Type' => __DIR__.'/lib/Elastica/Filter/Type.php',

	'Elastica_Index_Settings' => __DIR__.'/lib/Elastica/Index/Settings.php',
	'Elastica_Index_Stats' => __DIR__.'/lib/Elastica/Index/Stats.php',
	'Elastica_Index_Status' => __DIR__.'/lib/Elastica/Index/Status.php',

	'Elastica_Node_Info' => __DIR__.'/lib/Elastica/Node/Info.php',
	'Elastica_Node_Stats' => __DIR__.'/lib/Elastica/Node/Stats.php',

	'Elastica_Query_Abstract' => __DIR__.'/lib/Elastica/Query/Abstract.php',
	'Elastica_Query_Array' => __DIR__.'/lib/Elastica/Query/Array.php',
	'Elastica_Query_Bool' => __DIR__.'/lib/Elastica/Query/Bool.php',
	'Elastica_Query_Builder' => __DIR__.'/lib/Elastica/Query/Builder.php',
	'Elastica_Query_ConstantScore' => __DIR__.'/lib/Elastica/Query/ConstantScore.php',
	'Elastica_Query_CustomFiltersScore' => __DIR__.'/lib/Elastica/Query/CustomFiltersScore.php',
	'Elastica_Query_CustomScore' => __DIR__.'/lib/Elastica/Query/CustomScore.php',
	'Elastica_Query_Field' => __DIR__.'/lib/Elastica/Query/Field.php',
	'Elastica_Query_Filtered' => __DIR__.'/lib/Elastica/Query/Filtered.php',
	'Elastica_Query_Fuzzy' => __DIR__.'/lib/Elastica/Query/Fuzzy.php',
	'Elastica_Query_FuzzyLikeThis' => __DIR__.'/lib/Elastica/Query/FuzzyLikeThis.php',
	'Elastica_Query_HasChild' => __DIR__.'/lib/Elastica/Query/HasChild.php',
	'Elastica_Query_Ids' => __DIR__.'/lib/Elastica/Query/Ids.php',
	'Elastica_Query_MatchAll' => __DIR__.'/lib/Elastica/Query/MatchAll.php',
	'Elastica_Query_MoreLikeThis' => __DIR__.'/lib/Elastica/Query/MoreLikeThis.php',
	'Elastica_Query_Nested' => __DIR__.'/lib/Elastica/Query/Nested.php',
	'Elastica_Query_Prefix' => __DIR__.'/lib/Elastica/Query/Prefix.php',
	'Elastica_Query_QueryString' => __DIR__.'/lib/Elastica/Query/QueryString.php',
	'Elastica_Query_Range' => __DIR__.'/lib/Elastica/Query/Range.php',
	'Elastica_Query_Term' => __DIR__.'/lib/Elastica/Query/Term.php',
	'Elastica_Query_Terms' => __DIR__.'/lib/Elastica/Query/Terms.php',
	'Elastica_Query_Text' => __DIR__.'/lib/Elastica/Query/Text.php',
	'Elastica_Query_TopChildren' => __DIR__.'/lib/Elastica/Query/TopChildren.php',
	'Elastica_Query_Wildcard' => __DIR__.'/lib/Elastica/Query/Wildcard.php',
	
	'Elastica_Transport_Abstract' => __DIR__.'/lib/Elastica/Transport/Abstract.php',
	'Elastica_Transport_Http' => __DIR__.'/lib/Elastica/Transport/Http.php',
	'Elastica_Transport_Https' => __DIR__.'/lib/Elastica/Transport/Https.php',
	'Elastica_Transport_Memcache' => __DIR__.'/lib/Elastica/Transport/Memcache.php',

	'Elastica_Type_Abstract' => __DIR__.'/lib/Elastica/Type/Abstract.php',
	'Elastica_Type_Mapping' => __DIR__.'/lib/Elastica/Type/Mapping.php',
	
));